In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
books = pd.read_csv("books.csv")
users = pd.read_csv("users.csv")
ratings = pd.read_csv("ratings.csv")

C:\Users\ABHISHEK SENGAR\AppData\Local\Temp\ipykernel_2116\2028538187.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("books.csv")

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
books.duplicated().sum()

0

In [9]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [10]:
users.duplicated().sum()

0

In [11]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [12]:
ratings.duplicated().sum()

0

# Popular Based

In [13]:
ratings_with_name = ratings.merge(books,on="ISBN")

In [14]:
num_rating_df = ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [15]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'Average-Rating'},inplace=True)
avg_rating_df

C:\Users\ABHISHEK SENGAR\AppData\Local\Temp\ipykernel_2116\3511255232.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()

                                               Book-Title  Average-Rating
0        A Light in the Storm: The Civil War Diary of ...        2.250000
1                                   Always Have Popsicles        0.000000
2                    Apple Magic (The Collector's series)        0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...        8.000000
4        Beyond IBM: Leadership Marketing and Finance ...        0.000000
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.        0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.        5.250000
241068                                Ã?Â?sterlich leben.        7.000000
241069                              Ã?Â?stlich der Berge.        2.666667
241070                                  Ã?Â?thique en toc        4.000000

[241071 rows x 2 columns]

In [16]:
popular_df = num_rating_df.merge(avg_rating_df,on="Book-Title")
popular_df

,Book-Title,num_ratings,Average-Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [17]:
pupolar_df = popular_df[popular_df['num_ratings']>=250].sort_values('Average-Rating',ascending=False).head(50)

In [18]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','Average-Rating']]

In [19]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0590567330.01.MZZZZZZZ.jpg'

# Collaborative Filtering

In [20]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
users = x[x].index

In [21]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(users)]

In [22]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [23]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50

In [24]:
famous_book = y[y].index

In [25]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_book)]

In [26]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [27]:
pt.fillna(0,inplace=True)

In [28]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
similarity_scores = cosine_similarity(pt)

In [31]:
similarity_scores.shape

(706, 706)

In [32]:
print(similarity_scores)

[[1.         0.10255025 0.01220856 ... 0.12110367 0.07347567 0.04316046]
 [0.10255025 1.         0.2364573  ... 0.07446129 0.16773875 0.14263397]
 [0.01220856 0.2364573  1.         ... 0.04558758 0.04938579 0.10796119]
 ...
 [0.12110367 0.07446129 0.04558758 ... 1.         0.07085128 0.0196177 ]
 [0.07347567 0.16773875 0.04938579 ... 0.07085128 1.         0.10602962]
 [0.04316046 0.14263397 0.10796119 ... 0.0196177  0.10602962 1.        ]]

In [33]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    
    data = []
    
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title']==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
        
    return data

In [96]:
recommend(possible_book_name)

[['Harry Potter and the Goblet of Fire (Book 4)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439139597.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Prisoner of Azkaban (Book 3)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Chamber of Secrets (Book 2)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439064872.01.MZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Book 1)",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0590353403.01.MZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/059035342X.01.MZZZZZZZ.jpg']]

In [35]:
book_title = final_ratings['Book-Title'].drop_duplicates()

In [36]:
book_title = pd.DataFrame(book_title).reset_index()

In [37]:
book_title.head()

   index       Book-Title
0     63     The Notebook
1    184  A Painted House
2    368        Lightning
3    616    Dark Paradise
4    750       Night Sins

In [38]:
book_title = book_title.drop(['index'],axis=1)

In [39]:
print(book_title)

                            Book-Title
0                         The Notebook
1                      A Painted House
2                            Lightning
3                        Dark Paradise
4                           Night Sins
..                                 ...
701           Billy Straight : A Novel
702      Macgregor Grooms (Macgregors)
703                             Vector
704                A Great Deliverance
705  Deck the Halls (Holiday Classics)

[706 rows x 1 columns]

In [40]:
book_title = book_title.to_numpy().flatten()

In [41]:
print(book_title)

['The Notebook' 'A Painted House' 'Lightning' 'Dark Paradise' 'Night Sins'
 'How Stella Got Her Groove Back' 'Waiting to Exhale'
 'The Pillars of the Earth' 'The Dark Half'
 'Harry Potter and the Order of the Phoenix (Book 5)' 'False Memory'
 "Bridget Jones's Diary" 'A Wrinkle In Time' 'The Boy Next Door'
 'Artemis Fowl (Artemis Fowl, Book 1)' 'The Last Time They Met : A Novel'
 'Along Came a Spider (Alex Cross Novels)' 'Whispers'
 "Ender's Game (Ender Wiggins Saga (Paperback))" 'The Jester'
 'The King of Torts'
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times'
 'Matilda' 'The Lovely Bones: A Novel' 'The Da Vinci Code'
 'The Joy Luck Club' 'Wild Animus' 'Coraline'
 'Harry Potter and the Chamber of Secrets (Book 2)'
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))"
 'To Kill a Mockingbird' 'Four To Score (A Stephanie Plum Novel)'
 'Southern Cross' 'The Chamber' "The Idiot Girls' Action Adventure Club"
 'Dreamcatcher' 'All Around the Town' 'Winter Solstice' 'Deja Dead'
 'The Saving Graces: A Novel' "Full House (Janet Evanovich's Full Series)"
 'Mystic River' 'Roses Are Red (Alex Cross Novels)' 'Violets Are Blue'
 "The Sweet Potato Queens' Book of Love"
 "She's Come Undone (Oprah's Book Club (Paperback))" 'Choke' 'Hannibal'
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)'
 'The Summons' 'Mortal Prey' 'Fahrenheit 451' 'Flesh and Blood'
 'I Is for Innocent' 'Back Roads' 'Silent Witness' 'Angels &amp; Demons'
 'Black Notice' 'The Street Lawyer' 'The Bourne Supremacy' 'Bag of Bones'
 'The Green Mile' 'Big Trouble' 'Cradle and All' '1st to Die: A Novel'
 'Over the Edge' 'Sleepers' 'The Hot Zone' 'A Man in Full'
 "The Bonesetter's Daughter" 'Holes (Yearling Newbery)'
 'The Girl Who Loved Tom Gordon' 'The English Patient'
 "I Know This Much Is True (Oprah's Book Club)"
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel'
 'I Know This Much Is True' "Fortune's Rocks : A Novel"
 'The Blind Assassin' 'Breathing Lessons' 'The Brethren'
 'Jack &amp; Jill (Alex Cross Novels)'
 'Cat &amp; Mouse (Alex Cross Novels)' 'Dances With Wolves'
 'The Prince of Tides' 'The Alienist'
 "She's Come Undone (Oprah's Book Club)" 'SHIPPING NEWS'
 'Girl, Interrupted'
 'A Child Called \\It\\": One Child\'s Courage to Survive"'
 'The Beach House' 'White Teeth: A Novel' "Daddy's Little Girl"
 "The Hitchhiker's Guide to the Galaxy" 'The Stone Diaries'
 'Girl in Hyacinth Blue' 'The Devil Wears Prada : A Novel'
 'While I Was Gone' "The Pilot's Wife : A Novel"
 'Girl with a Pearl Earring' 'Chocolat' "From Potter's Field"
 'Little Altars Everywhere: A Novel' 'On the Street Where You Live'
 'Life of Pi' 'The Red Tent (Bestselling Backlist)'
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies'
 'A Walk to Remember' 'Thinner' 'I Know Why the Caged Bird Sings'
 'Bridget Jones : The Edge of Reason' 'The Temple of My Familiar'
 "Angela's Ashes (MMP) : A Memoir" 'The Poisonwood Bible: A Novel'
 'Bel Canto: A Novel'
 'One for the Money (Stephanie Plum Novels (Paperback))'
 'The Secret Garden' 'The Tao of Pooh' 'The Secret Life of Bees'
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)'
 "Full Tilt (Janet Evanovich's Full Series)" 'Lucky : A Memoir'
 'The Dogs of Babel (Today Show Book Club #12)'
 "White Oleander : A Novel (Oprah's Book Club)" 'White Oleander : A Novel'
 'Me Talk Pretty One Day' 'Naked'
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings'
 'A Prayer for Owen Meany' 'No Safe Place' 'The Murder Book'
 'Middlesex: A Novel' 'Postmortem'
 'All That Remains (Kay Scarpetta Mysteries (Paperback))' 'The Rainmaker'
 "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson"
 'Into the Wild' 'Oryx and Crake' 'Lord of the Flies' 'Watchers'
 'Mortal Fear' 'The Cardinal of the Kremlin (Jack Ryan Novels)'
 'Rules of Prey' 'Mind Prey' 'Contagion' 'Cause of Death' 'Certain Prey'
 'Harry Potter and the Prisoner of Azkaban (Book 3)'
 "Harry Potter and the Sorcerer's Stone (Book 1)" 'The Promise' 'Secrets'
 'Wanderlust' 'Guardian Angel' 'Vanished' 'The Partner' 'Tell No One'
 'Presumed Innocent' 'Blood Work' 'Hide &amp; Seek' 'Unspeakable'
 'Saving Faith' 'J Is for Judgment'
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))' 'Misery'
 'Dolores Claiborne' 'The Edge'
 'Heaven and Earth (Three Sisters Island Trilogy)' 'Hemlock Bay'
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))'
 'Where the Red Fern Grows'
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))'
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))'
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))'
 'Long After Midnight' 'One Door Away from Heaven'
 'By the Light of the Moon' 'Two for the Dough' 'The God of Small Things'
 'A Year in Provence' 'Midnight in the Garden of Good and Evil'
 'The Sands of Time' 'If Only It Were True' 'Pay It Forward'
 "The Kitchen God's Wife" 'Saint Maybe' 'A Patchwork Planet'
 'Tears of the Giraffe (No.1 Ladies Detective Agency)'
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)"
 'Balzac and the Little Chinese Seamstress : A Novel'
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))'
 "Hornet's Nest" '2nd Chance'
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))'
 'Small Town Girl' 'Still Waters'
 'A Thin Dark Line (Mysteries &amp; Horror)'
 'The Queen of the Damned (Vampire Chronicles (Paperback))' 'Night Prey'
 'Chromosome 6' 'Point of Origin' 'The Testament' 'When the Wind Blows'
 "A Thousand Acres (Ballantine Reader's Circle)" 'Ashes to Ashes'
 'Fear Nothing' 'Seize the Night' "I'll Be Seeing You"
 'The Five People You Meet in Heaven' 'All I Really Need to Know'
 'Fried Green Tomatoes at the Whistle Stop Cafe'
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))"
 "Charlotte's Web (Trophy Newbery)" 'Good in Bed' 'Bleachers' 'The Reader'
 'The Diary of Ellen Rimbauer: My Life at Rose Red' 'Disclosure'
 'The Thorn Birds' 'The Runaway Jury' 'WLD ACCORDNG GARP'
 "Don't Stand Too Close to a Naked Man" 'Dark Rivers of the Heart'
 'Whirlwind (Tyler, Book 1)' 'Rainbow Six' 'Shadow Prey'
 'The Sum of All Fears (Jack Ryan Novels)'
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))"
 'A Time to Kill' 'Heartbeat' 'The Client' 'The Pelican Brief'
 "Smilla's Sense of Snow" 'The Horse Whisperer' 'Pet Sematary'
 'Four Past Midnight' 'Fat Tuesday' 'Hideaway' "We'll Meet Again" 'Mercy'
 'Sea Swept (Quinn Brothers (Paperback))' 'The Shipping News : A Novel'
 'The Catcher in the Rye'
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))' 'Black House'
 'The Gunslinger (The Dark Tower, Book 1)'
 'The Drawing of the Three (The Dark Tower, Book 2)'
 'Wizard and Glass (The Dark Tower, Book 4)' "The Handmaid's Tale"
 'Beloved (Plume Contemporary Fiction)' 'Seabiscuit: An American Legend'
 'The Smoke Jumper' 'Drowning Ruth' 'Night' 'The Bean Trees' 'Rebecca'
 'The Surgeon' 'Neverwhere' 'Snow Falling on Cedars' 'Angels'
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel'
 "Where the Heart Is (Oprah's Book Club (Paperback))"
 'The Honk and Holler Opening Soon' 'Summer Sisters' 'Without Remorse'
 'Bastard Out of Carolina' 'Sole Survivor' 'The Switch' 'Intensity'
 'A Heartbreaking Work of Staggering Genius'
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster'
 'Circle of Friends' "Dude, Where's My Country?" 'The Virgin Suicides'
 'Midnight in the Garden of Good and Evil: A Savannah Story'
 'It Was on Fire When I Lay Down on It' 'Blessings' 'Falling Angels'
 'Tis: A Memoir' 'Fall On Your Knees (Oprah #45)' 'Welcome to Temptation'
 'Faking It' 'Scarlet Feather' 'Rising Tides'
 'Inner Harbor (Quinn Brothers (Paperback))'
 'Key of Light (Key Trilogy (Paperback))'
 'Key of Knowledge (Key Trilogy (Paperback))'
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)' 'Birthright'
 'The Empty Chair' 'The Woman Next Door' 'Sphere' 'The Andromeda Strain'
 'Congo' 'Rising Sun' 'Airframe' 'The Lost World' 'Timeline' 'Paradise'
 "ANGELA'S ASHES"
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)"
 'A Bend in the Road' 'Winter Moon' 'Red Dragon' 'Absolute Power'
 'Last Man Standing' 'The Bridges of Madison County' 'Different Seasons'
 'A Widow for One Year' 'P Is for Peril' 'Carolina Moon'
 'A Day Late and a Dollar Short' 'Guilty as Sin' 'Secret History'
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))"
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))'
 'The Wedding' 'About a Boy' 'House of Sand and Fog'
 'Five Quarters of the Orange' 'Interview with the Vampire'
 'Weep No More My Lady' 'Mirror Image' 'Tara Road' 'The Guardian'
 'Message in a Bottle' 'Let Me Call You Sweetheart'
 'While My Pretty One Sleeps' 'Remember Me' 'Second Nature'
 'The Last Precinct' 'Isle of Dogs' 'Fatherhood'
 'Debt of Honor (Jack Ryan Novels)' 'One True Thing' 'The Simple Truth'
 'Four Blind Mice' 'STONES FROM THE RIVER'
 "Dr. Atkins' New Diet Revolution" '1984' 'Evening Class'
 'Drums of Autumn' 'Icy Sparks' "Drowning Ruth (Oprah's Book Club)"
 'Engaging The Enemy' 'Irish Hearts' 'Red Storm Rising' 'Echoes'
 'Nothing Lasts Forever' 'Smart Women' 'Temptation'
 'Truly, Madly Manhattan'
 "Sophie's World: A Novel About the History of Philosophy"
 'Cold Sassy Tree' 'Peace Like a River' 'Prime Cut'
 'At Home in Mitford (The Mitford Years)' 'Fast Women'
 'The Long Road Home' 'Standoff' 'Envy' 'Wish You Well' 'Watership Down'
 'Sick Puppy' 'The Fellowship of the Ring (The Lord of the Rings, Part 1)'
 'Nerd in Shining Armor' 'Outlander'
 'Face the Fire (Three Sisters Island Trilogy)'
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)'
 'Harry Potter and the Goblet of Fire (Book 4)' 'The Robber Bride'
 'The Bachelor (Warner Books Contemporary Romance)'
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships'
 'The Little Prince' 'Coming Home'
 'The Vampire Lestat (Vampire Chronicles, Book II)' 'Beloved'
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure"
 "Foucault's Pendulum" 'Degree of Guilt' 'Icebound'
 'The Witching Hour (Lives of the Mayfair Witches)'
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))'
 'The Genesis Code' 'Ellen Foster' 'American Gods'
 "The Book of Ruth (Oprah's Book Club (Paperback))" 'No Greater Love'
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies'
 'The Phantom Tollbooth' 'Dragon Tears' 'Midnight'
 'The Hunt for Red October' 'Turtle Moon' 'Fatal Cure' 'The Body Farm'
 'Acceptable Risk' 'Invasion' 'Sudden Prey'
 'Executive Orders (Jack Ryan Novels)' 'Purity in Death' 'Family Album'
 'Daddy' 'The Firm' 'A Wrinkle in Time' 'Five Days in Paris'
 'The Return Journey' 'The Kiss'
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""'
 "The General's Daughter" 'The Witness' 'Slow Waltz in Cedar Bend'
 'Primary Colors: A Novel of Politics' 'Master of the Game'
 'Catering to Nobody' 'Christine' 'The Tommyknockers' 'Needful Things'
 "Gerald's Game" 'The Door to December' 'A Case of Need' 'Insomnia'
 'The Deep End of the Ocean' 'The Reef'
 'Jewels of the Sun (Irish Trilogy)' "River's End"
 'Tears of the Moon (Irish Trilogy)'
 'Dance upon the Air (Three Sisters Island Trilogy)' 'The Regulators'
 'Couplehood' 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))'
 'The Clinic (Alex Delaware Novels (Paperback))' 'Lake Wobegon Days'
 'My Gal Sunday' 'Hearts In Atlantis' 'Night Whispers' 'The Color Purple'
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))' 'Dawn (Cutler)'
 'Loves Music, Loves to Dance' 'Moonlight Becomes You' 'If Tomorrow Comes'
 'Dangerous' 'Call of the Wild' 'In Her Shoes : A Novel'
 "Suzanne's Diary for Nicholas" 'The Next Accident' 'Empire Falls'
 'Easy Prey' 'Chosen Prey' 'The Glass Lake' 'The Burden of Proof'
 '\\O\\" Is for Outlaw"'
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))'
 'The Killing Game: Only One Can Win...and the Loser Dies'
 'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values'
 'Plum Island' 'Final Target'
 'The Lottery Winner : Alvirah And Willy Stories'
 'The Subtle Knife (His Dark Materials, Book 2)'
 "The Girls' Guide to Hunting and Fishing"
 'High Five (A Stephanie Plum Novel)'
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)'
 'Seven Up (A Stephanie Plum Novel)'
 'One for the Money (A Stephanie Plum Novel)' 'The Mists of Avalon'
 'The Loop' 'River, Cross My Heart'
 "A Virtuous Woman (Oprah's Book Club (Paperback))"
 "Vinegar Hill (Oprah's Book Club (Paperback))" 'The Rescue'
 'We Were the Mulvaneys'
 'A Man Named Dave: A Story of Triumph and Forgiveness'
 "The Clan of the Cave Bear (Earth's Children (Paperback))" 'Jewel'
 'Possession : A Romance' 'Riptide' 'Digital Fortress : A Thriller'
 'N Is for Noose' 'The Summerhouse'
 'Chicken Soup for the Soul (Chicken Soup for the Soul)' 'Here on Earth'
 'M Is for Malice' 'The Cider House Rules' 'Brave New World'
 'Pigs in Heaven' 'Pride and Prejudice' 'From the Corner of His Eye'
 'Seabiscuit' "Pretend You Don't See Her" 'The Alibi'
 'Before I Say Good-Bye' 'Atonement : A Novel' 'Contact'
 'Plainsong (Vintage Contemporaries)' 'A Map of the World'
 'The Accidental Tourist' 'Unnatural Exposure' 'Deception Point'
 "Jewel (Oprah's Book Club)" 'Tis : A Memoir'
 'Wicked: The Life and Times of the Wicked Witch of the West'
 'The Alchemist: A Fable About Following Your Dream'
 'Bridget Jones: The Edge of Reason' 'The Hours: A Novel'
 'The Amber Spyglass (His Dark Materials, Book 3)'
 'The Golden Compass (His Dark Materials, Book 1)'
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies'
 'Good Omens' 'Animal Farm' 'The Valley of Horses' 'Sacred Sins'
 'The Two Towers (The Lord of the Rings, Part 2)'
 'The Perfect Storm : A True Story of Men Against the Sea'
 'Heart of the Sea (Irish Trilogy)' 'Black and Blue'
 'Nickel and Dimed: On (Not) Getting By in America'
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)"
 'The Nanny Diaries: A Novel' 'Three Junes' 'Strangers'
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal"
 "Angela's Ashes: A Memoir"
 "The Color of Water: A Black Man's Tribute to His White Mother"
 'The Mummy or Ramses the Damned'
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!'
 'Fast Food Nation: The Dark Side of the All-American Meal'
 'Daisy Fay and the Miracle Man' 'Cry Wolf' 'The Ugly Duckling'
 'Dust to Dust' 'Touching Evil' 'The Hours : A Novel' 'Skipping Christmas'
 'The Villa' 'Nights in Rodanthe' 'Welcome to the World, Baby Girl!'
 'FORREST GUMP (Movie Tie in)' 'The Giver (21st Century Reference)'
 'Charming Billy' 'Granny Dan' 'Toxin' 'The Bad Place' 'Wuthering Heights'
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))'
 'The Carousel' 'Dragonfly in Amber' 'The House of the Spirits'
 'Kiss the Girls' 'Jurassic Park' 'Bridge to Terabithia'
 'Stanislaski Brothers (Silhouette Promo)' 'Three Fates'
 'Forever... : A Novel of Good and Evil, Love and Hope'
 'Seven Habits Of Highly Effective People' 'Mother of Pearl'
 'Anne Frank: The Diary of a Young Girl'
 'Confessions of a Shopaholic (Summer Display Opportunity)'
 'Shopaholic Takes Manhattan (Summer Display Opportunity)'
 'Breath, Eyes, Memory' 'How to Make an American Quilt'
 'Cold Mountain : A Novel' 'A Civil Action' 'The Blue Nowhere : A Novel'
 'I Capture the Castle'
 "What to Expect When You're Expecting (Revised Edition)"
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)"
 'Miss Julia Speaks Her Mind : A Novel' 'Notes from a Small Island'
 'Harvest' 'The Poisonwood Bible' 'Year of Wonders' 'Pop Goes the Weasel'
 "Everything's Eventual : 14 Dark Tales" "CAT'S EYE" 'Body of Lies'
 'Now You See Her' 'Jemima J: A Novel About Ugly Ducklings and Swans'
 'Sea Glass: A Novel' 'The Copper Beech'
 'Dying for Chocolate (Culinary Mysteries (Paperback))'
 'Clear and Present Danger (Jack Ryan Novels)'
 'The Return of the King (The Lord of the Rings, Part 3)'
 'The First Counsel' 'Watermelon'
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))' 'How to Be Good'
 'Carnal Innocence' 'You Belong To Me'
 'Confessions of an Ugly Stepsister : A Novel' 'It' 'Midnight Bayou'
 'Wifey' 'Montana Sky' 'Homecoming' 'Phantoms' 'The Eight' 'The Gift'
 'The Bourne Ultimatum' 'The Eyre Affair: A Novel' 'Mr. Murder'
 'Midwives: A Novel' 'The Hundred Secret Senses'
 "Song of Solomon (Oprah's Book Club (Paperback))"
 'To the Nines: A Stephanie Plum Novel'
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)'
 "It's Always Something" 'Tales of a Fourth Grade Nothing' 'Animal Dreams'
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)'
 'A Fine Balance' 'Stillwatch' 'Slammerkin'
 "The Plains of Passage (Earth's Children (Paperback))" 'Desperation'
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))'
 'Pleading Guilty' '4 Blondes' 'The Great Gatsby'
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson'
 'Last Chance Saloon' 'The Talisman'
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)' 'Beach House'
 'Macgregor Brides (Macgregors)' 'Message from Nam' 'Sanctuary'
 'The Bourne Identity' 'Eyes of a Child' 'Q Is for Quarry'
 'Under the Tuscan Sun' 'Heartbreaker' 'Shopaholic Ties the Knot'
 'Ladder of Years' 'High Fidelity' 'Prodigal Summer' 'The Mulberry Tree'
 'Silence of the Lambs' 'The Rapture of Canaan'
 'What Looks Like Crazy On An Ordinary Day' 'Range of Motion'
 'The Reptile Room (A Series of Unfortunate Events, Book 2)'
 'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))'
 'The Pull of the Moon' 'The Bonfire of the Vanities' 'Rose Madder' 'Cujo'
 'Shell Seekers' 'Death du Jour'
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion'
 'The Search' 'The Celestine Prophecy (Celestine Prophecy)' 'Journey'
 'The Winner' 'Cold Mountain' 'Betrayal in Death' 'Violin'
 'Portrait in Death' 'L Is for Lawless' 'The Angel of Darkness'
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)'
 'The Fourth Hand' 'The Crimson Petal and the White' 'The Most Wanted'
 'All the Pretty Horses (The Border Trilogy, Vol 1)' 'Exclusive'
 'Taltos: Lives of the Mayfair Witches' 'Dark Angel' 'Shattered'
 'Skeleton Crew' "Schindler's List" 'The Other Boleyn Girl'
 'Jacob Have I Loved' 'Crazy for You' "Fortune's Rocks: A Novel"
 'Beach Music' 'Gorky Park' 'Blue Diary' 'Devices and Desires' 'Moo'
 'Fingersmith' 'Accident' 'Hearts in Atlantis' 'Voyager' 'Killjoy'
 'Fine Things' 'Nightmares &amp; Dreamscapes' 'The Face of Deception'
 'The Cradle Will Fall' 'Anne of the Island' 'Tell Me Lies (Tell Me Lies)'
 'Carrie' 'Dream Country' 'Summer Pleasures' 'Homeport' 'Colony'
 'Patriot Games (Jack Ryan Novels)' 'Zoya' 'Shadowfires' 'Practical Magic'
 'That Camden Summer' 'Kaleidoscope' 'Bittersweet'
 'Billy Straight : A Novel' 'Macgregor Grooms (Macgregors)' 'Vector'
 'A Great Deliverance' 'Deck the Halls (Holiday Classics)']

In [42]:
book_title.shape

(706,)

In [58]:
from fuzzywuzzy import process

In [104]:

process.extract(user_input, book_title, limit=5)
# print(possible_book_name)

[('Drowning Ruth', 77),
 ("Drowning Ruth (Oprah's Book Club)", 77),
 ('Holes (Yearling Newbery)', 64),
 ('The Drawing of the Three (The Dark Tower, Book 2)', 64),
 ('Bastard Out of Carolina', 64)]

In [102]:
recommend(possible_book_name)

[['The Reader',
  'Bernhard Schlink',
  'http://images.amazon.com/images/P/0679442790.01.MZZZZZZZ.jpg'],
 ['Breath, Eyes, Memory',
  'Edwidge Danticat',
  'http://images.amazon.com/images/P/037570504X.01.MZZZZZZZ.jpg'],
 ["Song of Solomon (Oprah's Book Club (Paperback))",
  'Toni Morrison',
  'http://images.amazon.com/images/P/0452260116.01.MZZZZZZZ.jpg'],
 ["Angela's Ashes: A Memoir",
  'Frank McCourt',
  'http://images.amazon.com/images/P/068484267X.01.MZZZZZZZ.jpg'],
 ['The Celestine Prophecy (Celestine Prophecy)',
  'James Redfield',
  'http://images.amazon.com/images/P/044651862X.01.MZZZZZZZ.jpg']]

In [109]:
author = final_ratings['Book-Author'].drop_duplicates().reset_index()

In [111]:
author = author.drop(['index'],axis=1)

In [113]:
author = author.to_numpy().flatten()

In [120]:
user_input = "Harry Potter"
process.extract(user_input, author, limit=5)

[('Eric L. Harry', 64),
 ('Harry Turtledove', 64),
 ('Peter Mayle', 58),
 ('Kerry Tucker', 58),
 ('Richard North Patterson', 57)]

In [121]:
process.extract(user_input, book_title, limit=5)

[('Harry Potter and the Order of the Phoenix (Book 5)', 90),
 ('Harry Potter and the Chamber of Secrets (Book 2)', 90),
 ("Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))", 90),
 ('Harry Potter and the Prisoner of Azkaban (Book 3)', 90),
 ("Harry Potter and the Sorcerer's Stone (Book 1)", 90)]